@echo off
setlocal enabledelayedexpansion

REM ══════════════════════════════════════════════════════════════════════
REM  SFS3 C++ Static Library Builder  (MSVC)
REM
REM  Usage:
REM    build_lib.bat           Static CRT (/MT), output SFS3_API.lib (normal)
REM    build_lib.bat /MTd      Only SFS3_API.cpp as /MTd -> SFS3_APId.lib (hxcpp objs stay /MT;
REM                            not usable alone with /MTd app — use for experiments only)
REM
REM  Prerequisites:
REM    1. Run "haxe build.hxml" first so that out\SFS3_API_CPP\ exists.
REM    2. Visual Studio 2022 installed (vcvars64 is called automatically).
REM
REM  Output:
REM    out\SFS3_API_CPP\dist\SFS3_API.h    — public header (copy)
REM    out\SFS3_API_CPP\dist\SFS3_API.lib  — combined static (Release /MT)
REM    out\SFS3_API_CPP\dist\SFS3_APId.lib — combined static (Debug /MTd)
REM ══════════════════════════════════════════════════════════════════════

set ROOT=%~dp0..
set OUT=%ROOT%\out\SFS3_API_CPP
set DIST=%OUT%\dist

set "MODE=RELEASE"
set "CL_EXTRA=/MT /O2"
set "OUT_LIB=SFS3_API.lib"
set "OUT_OBJ=SFS3_API.obj"
if /I "%~1"=="/MTd" set "MODE=DEBUG"
if /I "%~1"=="debug" set "MODE=DEBUG"
if /I "%~1"=="/debug" set "MODE=DEBUG"
if "!MODE!"=="DEBUG" (
  set "CL_EXTRA=/MTd /Zi /Od /D_DEBUG"
  set "OUT_LIB=SFS3_APId.lib"
  set "OUT_OBJ=SFS3_APId.obj"
)

REM ── Ensure x64 MSVC environment ──────────────────────────────────────
where cl >nul 2>&1
if errorlevel 1 (
    echo [*] Setting up MSVC x64 environment ...
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
    if errorlevel 1 (
        call "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
    )
    if errorlevel 1 (
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
    )
)
REM Even if cl.exe is on PATH, ensure we have the x64 target.
REM The hxcpp objects are x64; mismatched cl.exe (x86) causes LNK1112.
cl /Bv 2>&1 | findstr /i "x64" >nul
if errorlevel 1 (
    echo [*] Current cl.exe is not x64, re-initializing ...
    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
    if errorlevel 1 (
        call "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
    )
    if errorlevel 1 (
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1
    )
)

REM ── Verify hxcpp output exists ──────────────────────────────────────
if not exist "%OUT%\output.lib" (
    echo [!] %OUT%\output.lib not found.
    echo     Run "haxe build.hxml" first.
    exit /b 1
)

REM ── Auto-detect hxcpp include path ──────────────────────────────────
set HXCPP_INC=
for /f "delims=" %%i in ('haxelib path hxcpp 2^>nul') do (
    if exist "%%i\include\hxcpp.h" (
        set HXCPP_INC=%%i\include
    )
)
if "!HXCPP_INC!"=="" (
    echo [!] Could not find hxcpp include path.
    echo     Make sure hxcpp is installed: haxelib install hxcpp
    exit /b 1
)

REM ── Find the generated HxcppConfig header ───────────────────────────
set HXCPP_CFG=
for %%f in ("%OUT%\HxcppConfig*.h") do set HXCPP_CFG=%%~nxf
if "!HXCPP_CFG!"=="" (
    echo [!] HxcppConfig header not found in %OUT%.
    echo     Run "haxe build.hxml" first.
    exit /b 1
)

REM ── Find the obj directory (msvc*) ──────────────────────────────────
set OBJ_DIR=
for /d %%d in ("%OUT%\obj\msvc*") do set OBJ_DIR=%%d
if "!OBJ_DIR!"=="" (
    echo [!] No msvc obj directory found in %OUT%\obj\.
    exit /b 1
)

echo [*] Mode          : !MODE!
echo [*] hxcpp include : !HXCPP_INC!
echo [*] HxcppConfig   : !HXCPP_CFG!
echo [*] obj directory  : !OBJ_DIR!
echo [*] Output lib     : !OUT_LIB!
echo.

REM ── Compile SFS3_API.cpp ────────────────────────────────────────────
echo [*] Compiling SFS3_API.cpp ...
REM Copy the authoritative header first so every include path is up-to-date
copy /Y "%ROOT%\cpp\include\SFS3_API.h" "%OUT%\include\SFS3_API.h" >nul 2>nul

cl /nologo /c /EHsc /std:c++17 !CL_EXTRA! ^
    /DBUILDING_SFS3_API ^
    /FI"!HXCPP_CFG!" ^
    /I"%ROOT%\cpp\include" ^
    /I"%OUT%" ^
    /I"%OUT%\include" ^
    /I"!HXCPP_INC!" ^
    "%ROOT%\cpp\src\SFS3_API.cpp" ^
    /Fo:"%OUT%\!OUT_OBJ!"

if errorlevel 1 (
    echo.
    echo [!] Compilation failed.
    exit /b 1
)

REM ── Build response file from hxcpp's all_objs ──────────────────────
REM   The all_objs file (generated by hxcpp) lists every .obj with the
REM   correct paths and PCH references. We filter out __main__ and add
REM   our bridge object.
echo [*] Collecting object files ...
set RSP=%OUT%\sfs3_lib.rsp
echo "%OUT%\!OUT_OBJ!" > "%RSP%"

findstr /v /i "__main__" "%OBJ_DIR%\all_objs" >> "%RSP%"

REM ── Create combined static library ─────────────────────────────────
echo [*] Creating combined !OUT_LIB! ...
if not exist "%DIST%" mkdir "%DIST%"

pushd "%OUT%"
lib /nologo /OUT:"%DIST%\!OUT_LIB!" @"%RSP%"
popd

if errorlevel 1 (
    echo.
    echo [!] lib.exe merge failed.
    exit /b 1
)

del "%RSP%" 2>nul

REM ── Copy public headers ─────────────────────────────────────────────
copy /Y "%ROOT%\cpp\include\SFS3_API.h" "%DIST%\SFS3_API.h" >nul
copy /Y "%ROOT%\cpp\include\SFS3.hpp"   "%DIST%\SFS3.hpp"   >nul 2>nul
if not exist "%DIST%\sfs3" mkdir "%DIST%\sfs3"
xcopy /Y /Q "%ROOT%\cpp\include\sfs3\*.hpp" "%DIST%\sfs3\" >nul 2>nul

echo.
echo ════════════════════════════════════════════════════════════
echo  Done!  Distribute these files:
echo.
echo    %DIST%\SFS3_API.h
echo    %DIST%\SFS3.hpp
echo    %DIST%\sfs3\*.hpp
echo    %DIST%\SFS3_API.lib   ^(Release /MT^)
echo    %DIST%\SFS3_APId.lib  ^(Debug /MTd — run build_lib.bat /MTd^)
echo.
echo  Link example (MSVC):
echo    cl /EHsc app.cpp /I"dist" ^
echo       /link dist\SFS3_API.lib ^
echo       ws2_32.lib advapi32.lib crypt32.lib user32.lib
echo ════════════════════════════════════════════════════════════
