package sfs3.client.entities.invitation;

import sfs3.client.entities.User;
import sfs3.client.entities.data.ISFSObject;

/**
 * The <em>Invitation</em> interface defines all the methods and properties that an object representing an invitation entity exposes.
 * In the SmartFoxServer 3 client API this interface is implemented by the <em>SFSInvitation</em> class.
 *
 * @see SFSInvitation
 */
interface Invitation
{
	/**
	 * Indicates the id of this invitation.
	 * It is generated by the server when the invitation is sent.
	 */
	function getId():Int;

	/** @internal */
	function setId(id:Int):Void;

	/**
	 * Returns the <em>User</em> object corresponding to the user who sent the invitation.
	 */
	function getInviter():User;

	/**
	 * Returns the <em>User</em> object corresponding to the user who received the invitation.
	 */
	function getInvitee():User;

	/**
	 * Returns the number of seconds available to the invitee to reply to the invitation, after which the invitation expires.
	 */
	function getSecondsForAnswer():Int;

	/**
	 * Returns an instance of <em>SFSObject</em> containing a custom set of parameters.
	 * It usually stores invitation details, like a message to the invitee and any other relevant data.
	 */
	function getParams():ISFSObject;
}
