package sfs3.client.entities;

import sfs3.client.entities.managers.IRoomManager;
import sfs3.client.entities.variables.RoomVariable;

/**
 * <p>In the SmartFoxServer 3 client API this interface is implemented by the <em>SFSRoom</em> class. Read the class description for additional informations.</p>
 *
 * @see sfs3.client.entities.SFSRoom
 */

interface Room 
{
	/**
	 * The id of this Room.
	 * It is unique and it is generated by the server when the Room is created.
	 */
	function getId():Int;

	/**
	 * The unique name of this Room.
	 * Two Rooms in the same Zone can't have the same name (in a case sensitive way)
	 * 
	 * <p><b>NOTE</b>: setting the <em>name</em> property manually has no effect on the server and can disrupt the API functioning.
	 * Use the <em>ChangeRoomNameRequest</em> request instead.</p>
	 *
	 * @see sfs3.client.requests.ChangeRoomNameRequest
	 */
	function getName():String;

	/**
	 * @internal
	 */
	function setName(name:String):Void;

	/**
	 * Returns the Room Group name.
	 * Each Group is identified by a unique string (its name or id) and it represents a different "container" for Rooms.
	 * <p>Room Groups enable developers to organize Rooms under different types or categories and let clients select only those Groups they are interested in, in order to receive their events only.
	 * This is done via the <em>SubscribeRoomGroupRequest</em> and <em>UnsubscribeRoomGroupRequest</em> requests.</p>
	 * <p>The default value is <code>default.</code></p>
	 *
	 * @see sfs3.client.requests.SubscribeRoomGroupRequest
	 * @see sfs3.client.requests.UnsubscribeRoomGroupRequest
	 */
	function getGroupId():String;

	/**
	 * Indicates whether the client joined this Room or not.
	 * 
	 * <p><b>NOTE</b>: setting the <em>isJoined</em> property manually has no effect on the server and can disrupt the API functioning.
	 * Use the <em>JoinRoomRequest</em> request to join a new Room instead.</p>
	 *
	 * @see sfs3.client.requests.JoinRoomRequest
	 */
	function getJoined():Bool;

	/**
	 * Indicates whether this is a Game Room or not.
	 * 
	 * <p><b>NOTE</b>: setting the <em>isGame</em> property manually has no effect on the server and can disrupt the API functioning.
	 * This flag must be set when creating the Room.</p>
	 */

	function getGame():Bool;

	/**
	 * Indicates whether this Room is hidden or not.
	 * This is a utility flag that can be used by developers to hide certain Rooms from the interface of their application.
	 * 
	 * <p><b>NOTE</b>: setting the <em>isHidden</em> property manually has no effect on the server and can disrupt the API functioning.
	 * This flag must be set when creating the Room.</p>
	 */
	function getHidden():Bool;

	/**
	 * Indicates whether this Room requires a password to be joined or not.
	 * 
	 * <p><b>NOTE</b>: setting the <em>isPasswordProtected</em> property manually has no effect on the server and can disrupt the API functioning.
	 * This flag depends on the Room's password set when the Room is created or by means of the <em>ChangeRoomPasswordStateRequest</em> request.</p>
	 *
	 * @see sfs3.client.requests.ChangeRoomPasswordStateRequest
	 */
	function getPasswordProtected():Bool;

	/**
	 * @internal
	 */
	function setPasswordProtected(passwordProtected:Bool):Void;

	/**
	 * @internal
	 */
	function getManaged():Bool;

	/**
	 * Returns the current number of users in this Room.
	 * In case of Game Rooms, this is the number of players.
	 * 
	 * <p><b>NOTE</b>: setting the <em>userCount</em> property manually has no effect on the server and can disrupt the API functioning.
	 * This flag depends on the Room state.</p>
	 */
	function getUserCount():Int;


	/**
	 * Returns the maximum number of users allowed in this Room.
	 * In case of Game Rooms, this is the maximum number of players.
	 * 
	 * <p><b>NOTE</b>: setting the <em>maxUsers</em> property manually has no effect on the server and can disrupt the API functioning.
	 * This flag must be set when creating the Room.</p>
	 */
	function getMaxUsers():Int;

	/**
	 * Returns the current number of spectators in this Room (Game Rooms only).
	 * 
	 * <p><b>NOTE</b>: setting the <em>spectatorCount</em> property manually has no effect on the server and can disrupt the API functioning.
	 * This flag depends on the Room state.</p>
	 */
	function getSpectatorCount():Int;


	/**
	 * Returns the maximum number of spectators allowed in this Room (Game Rooms only).
	 * 
	 * <p><b>NOTE</b>: setting the <em>maxSpectators</em> property manually has no effect on the server and can disrupt the API functioning.
	 * This flag must be set when creating the Game Room.</p>
	 */
	function getMaxSpectators():Int;

	/**
	 * Returns the maximum amount of users, including spectators, that can be contained in this Room.
	 */
	function getCapacity():Int;

	/**
	 * @internal
	 */
	function setJoined(joined:Bool):Void;

	/**
	 * @internal
	 */
	function setGame(game:Bool):Void;

	/**
	 * @internal
	 */
	function setHidden(hidden:Bool):Void;

	/**
	 * @internal
	 */
	function setManaged(managed:Bool):Void;

	/**
	 * @internal
	 */
	function setUserCount(userCount:Int):Void;

	/**
	 * @internal
	 */
	function setMaxUsers(maxUsers:Int):Void;

	/**
	 * @internal
	 */
	function setSpectatorCount(spectatorCount:Int):Void;

	/**
	 * @internal
	 */
	function setMaxSpectators(maxSpectators:Int):Void;

	/**
	 * @internal
	 */
	function addUser(user:User):Void;

	/**
	 * @internal
	 */
	function removeUser(user:User):Void;

	/**
	 * Indicates whether the specified user is currently inside this Room or not.
	 *
	 * @param	user	The <em>User</em> object representing the user whose presence in this Room must be checked.
	 * @return	<code>true</code> if the user is inside this Room; <code>false</code> otherwise.
	 */
	function containsUser(user:User):Bool;

	/**
	 * Retrieves a <em>User</em> object from its <em>name</em> property.
	 *
	 * @param	name	The name of the user to be found.
	 * @return The <em>User</em> object representing the user, or <code>null</code> if no user with the passed name exists in this Room.
	 * 
	 * @see		#getUserById(id:Int)
	 */
	function getUserByName(name:String):User;

	/**
	 * Retrieves a <em>User</em> object from its <em>id</em> property.
	 *
	 * @param	id	The id of the user to be found.
	 * @return The <em>User</em> object representing the user, or <code>null</code> if no user with the passed id exists in this Room.
	 * 
	 * @see		#getUserByName(name:String)
	 */
	function getUserById(id:Int):User;

	/**
	 * Returns a list of <em>User</em> objects representing all the users currently inside this Room.
	 */
	function getUserList():Array<User>;

	/**
	 * Returns a list of <em>User</em> objects representing the players currently inside this Room (Game Rooms only).
	 */
	function getPlayerList():Array<User>;

	/**
	 * Returns a list of <em>User</em> objects representing the spectators currently inside this Room (Game Rooms only).
	 */
	function getSpectatorList():Array<User>;

	/**
	 * Retrieves a Room Variable from its name.
	 *
	 * @param	name	The name of the Room Variable to be retrieved.
	 * @return The <em>RoomVariable</em> object representing the Room Variable, or <code>null</code> if no Room Variable with the passed name exists in this Room.
	 * 
	 * @see		#getVariables()
	 * @see sfs3.client.requests.SetRoomVariablesRequest
	 */
	function getVariable(name:String):RoomVariable;

	/**
	 * Retrieves all the Room Variables of this Room.
	 *
	 * @return The list of <em>RoomVariable</em> objects associated with this Room.
	 * 
	 * @see		#getVariable(name:String)
	 * @see		sfs3.client.entities.variables.RoomVariable
	 */
	function getVariables():Array<RoomVariable>;

	/**
	 * @internal
	 */
	function setVariable(roomVariable:RoomVariable):Void;

	/**
	 * @internal
	 */
	function setVariables(roomVariables:Array<RoomVariable>):Void;

	/**
	 * Indicates whether this Room has the specified Room Variable set or not.
	 *
	 * @param	name	The name of the Room Variable whose existance in this Room must be checked.
	 * @return	<code>true</code> if a Room Variable with the passed name exists in this Room.
	 */
	function containsVariable(name:String):Bool;

	/**
	 * Returns a reference to the Room Manager which manages this Room.
	 *
	 * <p><b>NOTE</b>: setting the <em>roomManager</em> property manually has no effect on the server and can disrupt the API functioning.</p>
	 */
	function getRoomManager():IRoomManager;

	/**
	 * @internal
	 */
	function setRoomManager(manager:IRoomManager):Void;
	
	/**
	 * Indicates whether audio streaming is allowed in the Room.
	 * @return true if streaming is allowed
	 */
	function getAudioStreamingAllowed():Bool;
	
	/**
	 * @see #isAudioStreamingAllowed() 
	 */
	function setAudioStreamingAllowed(value:Bool):Void;
}
