package com.smartfoxserver.v3.entities;

import com.smartfoxserver.v3.entities.managers.IUserManager;
import com.smartfoxserver.v3.entities.variables.UserVariable;
import com.smartfoxserver.v3.entities.data.Vec3D;

/**
 * <p>In the SmartFoxServer 3 API this interface is implemented by the <em>SFSUser</em> class. Read the class description for additional information.</p>
 *
 * @see com.smartfoxserver.v3.entities.SFSUser
 */
interface User 
{
	/**
	 * The id of this user.
	 * It is unique and it is generated by the server when the user is created.
	 */
	function getId():Int;

	/**
	 * The name of this user.
	 * Two users in the same Zone can't have the same name (case sensitive)
	 */
	function getName():String;

	/**
	 * Returns the id of this user as a player in a Game Room.
	 * <p/>
	 * <p>This property differs from the <em>id</em> property and it's used to indicate which player number is assigned to a user inside a Game Room.
	 * For example, in a Game Room for 5 players the first client joining it will have <em>playerId</em> equal to <code>1</code>, the second will have it equal to <code>2</code> and so forth.
	 * When a user leaves the Room the player slot is freed up and the next user joining the Room will take it.</p>
	 * <p/>
	 * <p>The <em>playerId</em> property applies to Game Rooms only; in standard Rooms it is always <code>0</code>.
	 * Also, in Game Rooms a <em>playerId</em> value lower than <code>0</code> indicates that the user is a spectator.</p>
	 * <p/>
	 * <p>If the user is inside multiple Game Rooms at the same time, a different <em>playerId</em> value will be assigned to him in each Room.
	 * In this case this property returns the value corresponding to the last joined Room; in order to obtain the <em>playerId</em> value in a specific Room, use the <em>getPlayerId()</em> method.</p>
	 *
	 * @see		#getPlayerId(room:Room)
	 */
	function getPlayerId():Int;


	/**
	 * Indicates whether this user is a player (<em>playerId</em> greater than <code>0</code>) in the last joined Room or not.
	 * Non-Game Rooms always return <code>false</code>.
	 * <p/>
	 * <p>If the user is inside multiple Game Rooms at the same time, use the <em>isPlayerInRoom()</em> method.</p>
	 *
	 * @see 	#getPlayerId()
	 * @see		#isPlayerInRoom(room:Room)
	 * @see 	#isSpectator()
	 */
	function isPlayer():Bool;

	/**
	 * Indicates whether this user is a spectator (<em>playerId</em> lower than <code>0</code>) in the last joined Room or not.
	 * Non-Game Rooms always return <code>false</code>.
	 * <p/>
	 * <p>If the user is inside multiple Game Rooms at the same time, use the <em>isSpectatorInRoom()</em> method.</p>
	 *
	 * @see 	#getPlayerId()
	 * @see		#isSpectatorInRoom(room:Room)
	 * @see 	#isPlayer()
	 */
	function isSpectator():Bool;

	/**
	 * Returns the <em>playerId</em> value of this user in the passed Room.
	 * See the <em>playerId</em> property description for more informations.
	 *
	 * @param	room	The <em>Room</em> object representing the Room to retrieve the player id from.
	 * @return The <em>playerId</em> of this user in the passed Room.
	 * 
	 * @see		#getPlayerId()
	 */
	function getPlayerIdByRoom(room:Room):Int; // Not using method overloading to avoid confusion in Haxe (original was getPlayerId)

	/**
	 * @internal
	 */
	function setPlayerId(id:Int, room:Room):Void;

	/**
	 * @internal
	 */
	function removePlayerId(room:Room):Void;

	/**
	 * Returns the id which identifies the privilege level of this user.
	 * <p/>
	 * <p><b>NOTE</b>: setting the <em>privilegeId</em> property manually has no effect on the server and can disrupt the API functioning.
	 * Privileges are assigned to the user by the server when the user logs in.</p>
	 *
	 * @see com.smartfoxserver.v3.entities.UserPrivileges
	 */
	function getPrivilegeId():Int;

	/**
	 * @internal
	 */
	function setPrivilegeId(privilegeId:Int):Void;

	/**
	 * Returns a reference to the User Manager which manages this user.
	 * <p/>
	 * <p><b>NOTE</b>: setting the <em>userManager</em> property manually has no effect on the server and can disrupt the API functioning.</p>
	 */
	function getUserManager():IUserManager;

	/**
	 * @internal
	 */
	function setUserManager(userManager:IUserManager):Void;

	//--------------------------------------------------

	/**
	 * Indicates whether this user logged in as a guest or not.
	 * Guest users have the <em>privilegeId</em> property se to <em>UserPrivileges.GUEST</em>.
	 *
	 * @return	<code>true</code> if this user is a guest.
	 * 
	 * @see		#isStandardUser()
	 * @see		#isModerator()
	 * @see		#isAdmin()
	 * @see		#getPrivilegeId()
	 * @see		com.smartfoxserver.v3.entities.UserPrivileges#GUEST
	 */
	function isGuest():Bool;

	/**
	 * Indicates whether this user logged in as a standard user or not.
	 * Standard users have the <em>privilegeId</em> property se to <em>UserPrivileges.STANDARD</em>.
	 *
	 * @return	<code>true</code> if this user is a standard user.
	 * 
	 * @see		#isGuest()
	 * @see		#isModerator()
	 * @see		#isAdmin()
	 * @see		#getPrivilegeId()
	 * @see		com.smartfoxserver.v3.entities.UserPrivileges#STANDARD
	 */
	function isStandardUser():Bool;

	/**
	 * Indicates whether this user logged in as a moderator or not.
	 * Moderator users have the <em>privilegeId</em> property set to <em>UserPrivileges.MODERATOR</em>.
	 *
	 * @return	<code>true</code> if this user is a moderator.
	 * 
	 * @see		#isGuest()
	 * @see		#isStandardUser()
	 * @see		#isAdmin()
	 * @see		#getPrivilegeId()
	 * @see		com.smartfoxserver.v3.entities.UserPrivileges#MODERATOR
	 */
	function isModerator():Bool;

	/**
	 * Indicates whether this user logged in as an administrator or not.
	 * Administrator users have the <em>privilegeId</em> property set to <em>UserPrivileges.ADMINISTRATOR</em>.
	 *
	 * @return	<code>true</code> if this user is an administrator.
	 * 
	 * @see		#isGuest()
	 * @see		#isStandardUser()
	 * @see		#isModerator()
	 * @see		#getPrivilegeId()
	 * @see		com.smartfoxserver.v3.entities.UserPrivileges#ADMINISTRATOR
	 */
	function isAdmin():Bool;
	//--------------------------------------------------

	/**
	 * Indicates whether this user is a player (<em>playerId</em> greater than <code>0</code>) in the passed Room or not.
	 * Non-Game Rooms always return <code>false</code>.
	 * <p/>
	 * <p>If a user can join one Game Rooms at a time only, use the <em>isPlayer</em> property.</p>
	 *
	 * @param	room	The <em>Room</em> object representing the Room where to check if this user is a player.
	 * @return	<code>true</code> if this user is a player in the passed Room.
	 * 
	 * @see 	#getPlayerId()
	 * @see		#isPlayer()
	 * @see		#isSpectatorInRoom(room:Room)
	 */
	function isPlayerInRoom(room:Room):Bool;

	/**
	 * Indicates whether this user is a spectator (<em>playerId</em> lower than <code>0</code>) in the passed Room or not.
	 * Non-Game Rooms always return <code>false</code>.
	 * <p/>
	 * <p>If a user can join one Game Rooms at a time only, use the <em>isSpectator</em> property.</p>
	 *
	 * @param	room	The <em>Room</em> object representing the Room where to check if this user is a spectator.
	 * @return	<code>true</code> if this user is a spectator in the passed Room.
	 * 
	 * @see 	#getPlayerId()
	 * @see		#isSpectator()
	 * @see		#isPlayerInRoom(room:Room)
	 */
	function isSpectatorInRoom(room:Room):Bool;

	/**
	 * Indicates whether this user joined the passed Room or not.
	 *
	 * @param	room	The <em>Room</em> object representing the Room where to check the user presence.
	 * @return	<code>true</code> if this user is inside the passed Room.
	 */
	function isJoinedInRoom(room:Room):Bool;

	/**
	 * Indicates if this <em>User</em> object represents the current client.
	 */
	function getIsItMe():Bool;

	/**
	 * Retrieves all the User Variables of this user.
	 *
	 * @return The list of <em>UserVariable</em> objects associated with the user.
	 * 
	 * @see		com.smartfoxserver.v3.entities.variables.UserVariable
	 * @see		#getVariable()
	 */
	function getVariables():Array<UserVariable>;

	/**
	 * Retrieves a User Variable from its name.
	 *
	 * @param	varName	The name of the User Variable to be retrieved.
	 * @return The <em>UserVariable</em> object representing the User Variable, or <code>null</code> if no User Variable with the passed name is associated with this user.
	 * 
	 * @see		#getVariables()
	 * @see 	com.smartfoxserver.v3.requests.SetUserVariablesRequest
	 */
	function getVariable(varName:String):UserVariable;

	/**
	 * @internal
	 */
	function setVariable(userVariable:UserVariable):Void;

	/**
	 * @internal
	 */
	function setVariables(userVariables:Array<UserVariable>):Void;

	/**
	 * Indicates whether this user has the specified User Variable set or not.
	 *
	 * @param	name	The name of the User Variable whose existence must be checked.
	 * @return	<code>true</code> if a User Variable with the passed name is set for this user.
	 */
	function containsVariable(name:String):Bool;

	/**
	 * Returns the entry point within the User's AOI where this client "appeared" with the last
	 * PROXIMITY_LIST_UPDATE event. This field is populated only if the MMORoom is configured to receive this data.
	 * 
	 * @see com.smartfoxserver.v3.requests.mmo.MMORoomSettings
	 * @see com.smartfoxserver.v3.core.SFSEvent#PROXIMITY_LIST_UPDATE
	 */
	function getAOIEntryPoint():Vec3D<Any>;
	
	/** @internal */
	function setAOIEntryPoint(aoiEntryPoint:Vec3D<Any>):Void;
}
