name: Build Artifacts

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup Node.js dependencies
        run: npm install -g shx
      - uses: krdlab/setup-haxe@v1
      - name: Set up Haxelib dependencies
        run: |
          haxelib install crypto
          haxelib install colyseus-websocket
          haxelib install haxe-concurrent
          haxelib install hxjava
          haxelib git air https://github.com/tobil4sk/air
          haxelib install hxnodejs
          haxelib install hxcpp
      - name: Build libraries
        run: haxe build.hxml
      - uses: actions/upload-artifact@v7
        with:
          name: SFS3_API_JVM.jar
          path: out/SFS3_API_JVM.jar
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        with:
          name: SFS3_API_PY.py
          path: out/SFS3_API_PY.py
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        with:
          name: SFS3_API_AS3.swc
          path: out/SFS3_API_AS3.swc
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        with:
          name: SFS3_API_JS.js
          path: out/SFS3_API_JS.js
          if-no-files-found: error
      - uses: actions/upload-artifact@v7
        with:
          name: SFS3_API_Node.js
          path: out/SFS3_API_Node.js
          if-no-files-found: error